config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :videos do
  	resources :reviews
  end

  root 'videos#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :videos
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :video
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :videos
	has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
	has_many :reviews

	has_attached_file :video_img, styles: { video_index: "250x350>", video_show: "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :video_img, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_video
	before_action :find_review, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.video_id = @video.id
		@review.user_id = current_user.id

		if @review.save
			redirect_to video_path(@video)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @review.update(review_params)
			redirect_to video_path(@video)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to video_path(@video)
	end

	private
		def review_params
			params.require(:review).permit(:rating, :comment)
		end

		def find_video
			@video = Video.find(params[:video_id])
		end

		def find_review
			@review = Review.find(params[:id])
		end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	before_action :find_video, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def index
		if params[:category].blank?
			@videos = Video.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@videos = Video.where(:category_id => @category_id).order("created_at DESC")
		end
	end

	def show
		if @video.reviews.blank?
			@average_review = 0
		else
			@average_review = @video.reviews.average(:rating).round(2)
		end
	end

	def new
		#@video = Video.new
		@video = current_user.videos.build
		@categories = Category.all.map{|c| [c.name, c.id]}
	end

	def create
		#@video = Video.new(video_params)
		@video = current_user.videos.build(video_params)
		@video.category_id = params[:category_id]

		if @video.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		@categories = Category.all.map{|c| [c.name, c.id]}
	end

	def update
		@video.category_id = params[:category_id]
		if @video.update(video_params)
			redirect_to video_path(@video)
		else
			render 'edit'
		end
	end

	def destroy
		@video.destroy
		redirect_to root_path
	end

	private

		def video_params
			params.require(:video).permit(:name, :description, :director, :category_id, :video_img)
		end

		def find_video
			@video = Video.find(params[:id])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VideoStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container">
			
			<div class="navbar-header">
				<%= link_to "Video Review", root_path, class: "navbar-brand" %>
			</div>
			<ul class="nav navbar-nav">
				<li><%= link_to "Sing Up", new_user_registration_path %></li>
				<% if user_signed_in? %>
					<li><%= link_to "Sing Out", destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li><%= link_to "Log In", new_user_session_path %></li>
				<% end %>
			</ul>

			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<% Category.all.each do |c| %>
							<li class="<%= 'active' if params[:category] == c.name %>">
								<%= link_to c.name, videos_path(category: c.name), class: "link" %>
							</li>
						<% end %>
					</ul>
				</li>

				<% if user_signed_in? %>
					<li><%= link_to "Add Video", new_video_path %></li>
				<% end %>
			</ul>

		</div>
	</nav>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@video, @video.reviews.build]) do |f| %>
	<div id="rating-form">
		<% f.input :rating %>
		<label>Rating</label>
	</div>
	<%= f.input :comment %>
	<%= f.button :submit, :class => "btn-custom2" %>
<% end %>

<script type="text/javascript">
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="review">
	<div class="review-rating" data-score="<%= review.rating %>"></div>
	<p class="review-comment"><%= review.comment %></p>

	<% if user_signed_in? %>
		<% if current_user.id == review.user_id %>
			<div class="links btn-groups">
				<%= link_to "Edit", edit_video_review_path(review.video, review), class: "btn btn-custom" %>
				<%= link_to "Delete", video_review_path(review.video, review), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-custom" %>
			</div>
		<% end %>
	<% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="edit-review-form">

		<h1>Edit Review</h1>

		<%= simple_form_for([@video, @review]) do |f| %>
			<div id="rating-form">
				<% f.input :rating %>
				<label>Rating</label>
			</div>
			<%= f.input :comment %>
			<%= f.button :submit, :class => "btn-custom2" %>
		<% end %>

	</div>
</div>

<script type="text/javascript">
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="new-review-form">

		<h1>New Review</h1>
		<%= render 'form' %>
	
	</div>
</div>

app/views/videos/_form.html.erb
<%= simple_form_for @video, :html => {:multipart => true} do |v| %>
	<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
	<%= v.file_field :video_img%>
	<%= v.input :name %>
	<%= v.input :description, label: "Video Name"  %>
	<%= v.input :director %>
	<%= v.button :submit, :class => "btn-custom2" %>
<% end %>

app/views/videos/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="edit-video-form">

		<h1>Edit Video</h1>

		<%= simple_form_for @video, :html => {:multipart => true} do |v| %>
			<%= v.select :category_id, @categories %>
			<%= v.file_field :video_img%>
			<%= v.input :name %>
			<%= v.input :description, label: "Video Name"  %>
			<%= v.input :director %>
			<%= v.button :submit, :class => "btn-custom2" %>
		<% end %>

	</div>
</div>

app/views/videos/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>
<% if @videos.count == 0 %>

	<h1>There are no videos in this category</h1>

<% else %>
	
	<div class="row">
		<% @videos.each do |v| %>
			
			<div class="col-md-3">
				<a href="/videos/<%= v.id %>">
					<%= image_tag v.video_img.url(:video_index), class: "video" %>
				</a>
				<!--<h2><% link_to v.name, video_path(v) %></h2> -->
			</div>

		<% end %>
	</div>

<% end %>

app/views/videos/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="new-video-form">

		<h1>New Video</h1>
		<%= render 'form' %>

	</div>
</div>

app/views/videos/show.html.erb
<div class="row">

	<div class="col-md-4">
		<%= image_tag @video.video_img.url(:video_show), class: "video-show" %>
	</div>

	<div class="col-md-8">
		<div class="video-info">

			<h2 class="video-name"><%= @video.name %></h1>
			<h3 class="video-director"><span>Of </span><%= @video.director %></h3>
			<h2 class="avg-rating">Average Rating</h2>
			<div class="average-review-rating" data-score=<%= @average_review %>></div>
			<span class="number-of-reviews">Based on <%= @video.reviews.count %> reviews</span>
			<p class="video-desc"><%= @video.description %></p>

		</div>
	</div>

</div>

<div class="row">
	<div class="col-md-4">
		<div class="reviews">

			<h1>Reviews</h1>
			<%= render @video.reviews %>
			<div>
				<%= link_to "Add Review", new_video_review_path(@video), class: "btn-custom" %>
			</div>

		</div>
	</div>
</div>

<div class="links btn-group">

	<%= link_to "Back", root_path, class: "btn btn-custom" %>
	<% if user_signed_in? %>
		<% if @video.user_id == current_user.id %>
			<%= link_to "Edit", edit_video_path(@video), class: "btn btn-custom" %>
			<%= link_to "Delete", video_path(@video), method: :delete, data: { confirm: "Are you sure? " }, class: "btn btn-custom" %>
		<% end %>
	<% end %>

</div>

<script type="text/javascript">
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	})
</script>

<script type="text/javascript">
	$('.average-review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	})
</script>